#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9
do
  	sleep 1
        echo 1 > /sys/class/leds/beaglebone\:green\:usr3/brightness
        sleep 1
        echo 0 > /sys/class/leds/beaglebone\:green\:usr3/brightness
done
